NAME _PROGRAM ; 
BODY DATA INTEGER16 _VALUEIN , _DEVIDER , _REMAIND , _CYCLEAC , _CYCLEBC , _CYCLECC ;
  GET ( _VALUEIN )
  1 + _VALUEIN >> _VALUEIN
  FOR  0 >> _CYCLEAC TO 32767 DO
    _VALUEIN - 1 >> _DEVIDER
    FOR  0 >> _CYCLEBC TO 32767 DO 
      IF ( _DEVIDER >= 2 ) ; ELSE GOTO _ENDCYCB ;
      _VALUEIN >> _REMAIND
      FOR  0 >> _CYCLECC TO 32767 DO
        IF ( _REMAIND >= _DEVIDER ) ; ELSE GOTO _ENDCYCC ;
        _REMAIND - _DEVIDER >> _REMAIND
      ;
      _ENDCYCC :
      IF ( _REMAIND == 0 ) GOTO _ENDCYCB ;
      _DEVIDER - 1 >> _DEVIDER
    ;
    _ENDCYCB :
    IF ( _DEVIDER == 1 ) GOTO _ENDCYCA ;
    1 + _VALUEIN >> _VALUEIN
  ;
  _ENDCYCA :
  PUT ( _VALUEIN )
END
