NAME _PROGRAM ; 
BODY DATA INTEGER16 _BBBBBBB , _DDDDDDD , _EEEEEEE , _KKKKKKK ;
  25630 >> _KKKKKKK
  GET ( _BBBBBBB )
  GET ( _DDDDDDD )
  GET ( _EEEEEEE )
  PUT ( _KKKKKKK + _BBBBBBB - _DDDDDDD DIV 2 + _EEEEEEE * 4 )
END
